openapi: 3.0.0
openapi: 3.0.0
info:
  title: Social App
  description: This docs is for social app and it's api usecase - Jayakumar 
  version: 1.0.1
servers:
  - url: http://localhost:3000/api/v1/
    description: Optional server description, e.g. Main (production) server
  - url: https://localhost:3000/api/v1/ api-name
    description: This is just an dummy url. This doesn't work

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
    OpenID:
      type: openIdConnect
      openIdConnectUrl: https://example.com/.well-known/openid-configuration
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://example.com/oauth/authorize
          tokenUrl: https://example.com/oauth/token
          scopes:
            read: Grants read access
            write: Grants write access
            admin: Grants access to admin operations


#paths

paths:
     /instagram:
       get:
         summary: Return username,age,follwers,follows
         responses:
          "200" : #Status code
            description: return an object
            content: 
              application/json:
                schema:
                type: object
                   properties:
                      username:
                        type: string
                      Follwers: 
                        type: string
                      Follows:
                        type: string
                     date: 
                       type: number
       
       
       post:
         summary: Return username,age,follwers,follows
         responses:
          "200" : #Status code
            description: return an object
            content: 
              application/json:
                schema:
                  type: object
                    properties:
                      username:
                        type: string
                      Follwers: 
                        type: string
                      Follows:
                        type: string
                     date: 
                       type: number
     /{token}:
        get:
         summary: Return username specified token 
         parameters:
           - name: token
             default: 5
             in: path
             schema: 
                type: string

         responses:
          "200" : #Status code
            description: return an object
            content: 
              application/json:
                schema:
                type: object
                   properties:
                      param:
                        type: string

